site_name: skyCProgrammingRules
theme: material
site_author: XueYuSky
site_url: https://xueyusky.github.io/skyCProgrammingRules
repo_url: https://github.com/xueyusky/skyCProgrammingRules
copyright: xueyusky